[package]
name = "nauvi"
version = "0.1.0"
edition = "2021"
description = "Context-aware javascript codegen"
authors = ["Oliwier Michalik"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
